//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time to go back to work!.
        /// </summary>
        internal static string BackToWork {
            get {
                return ResourceManager.GetString("BackToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breaks.
        /// </summary>
        internal static string Breaks {
            get {
                return ResourceManager.GetString("Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurations.
        /// </summary>
        internal static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration (min).
        /// </summary>
        internal static string DurationMin {
            get {
                return ResourceManager.GetString("DurationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An  error occurred when deleting the history.
        /// </summary>
        internal static string ErrorDeleteHistory {
            get {
                return ResourceManager.GetString("ErrorDeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when saving the configuration.
        /// </summary>
        internal static string ErrorSaveConfiguration {
            get {
                return ResourceManager.GetString("ErrorSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let´s go.
        /// </summary>
        internal static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can now have a long break....
        /// </summary>
        internal static string LongBreak {
            get {
                return ResourceManager.GetString("LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Long break time.
        /// </summary>
        internal static string LongBreaks {
            get {
                return ResourceManager.GetString("LongBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Long Break.
        /// </summary>
        internal static string LongBreakSet {
            get {
                return ResourceManager.GetString("LongBreakSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pomodoros for long break.
        /// </summary>
        internal static string NumberPomodoro {
            get {
                return ResourceManager.GetString("NumberPomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pomodoro.
        /// </summary>
        internal static string Pomodoro {
            get {
                return ResourceManager.GetString("Pomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pomodoros.
        /// </summary>
        internal static string Pomodoros {
            get {
                return ResourceManager.GetString("Pomodoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete your history?.
        /// </summary>
        internal static string QuestionDeleteHistory {
            get {
                return ResourceManager.GetString("QuestionDeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart History.
        /// </summary>
        internal static string RestartHistory {
            get {
                return ResourceManager.GetString("RestartHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can now have a short break....
        /// </summary>
        internal static string ShortBreak {
            get {
                return ResourceManager.GetString("ShortBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Short break time.
        /// </summary>
        internal static string ShortBreaks {
            get {
                return ResourceManager.GetString("ShortBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shork Break.
        /// </summary>
        internal static string ShortBreakSet {
            get {
                return ResourceManager.GetString("ShortBreakSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start / Pause.
        /// </summary>
        internal static string StartPause {
            get {
                return ResourceManager.GetString("StartPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The history was successfully deleted.
        /// </summary>
        internal static string SuccessDeleteHistory {
            get {
                return ResourceManager.GetString("SuccessDeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save configuration successfully.
        /// </summary>
        internal static string SuccessSaveConfiguration {
            get {
                return ResourceManager.GetString("SuccessSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary per day.
        /// </summary>
        internal static string SummaryDay {
            get {
                return ResourceManager.GetString("SummaryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take a break!.
        /// </summary>
        internal static string TakeABreak {
            get {
                return ResourceManager.GetString("TakeABreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pomodoro time.
        /// </summary>
        internal static string TimePomodoro {
            get {
                return ResourceManager.GetString("TimePomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
